### ISSUE TITLE
Forever does not respond to SIGTERM?

### ISSUE THREAD

**Issue by adams-family** [foreversd/forever#1092]
I think that `forever` does not react to SIGTERM signal in any way. Here is an example:

Given the following setup in Docker:

```yml
# docker-compose.yml
version: "3.7"
services:
  node:
    build: .
    restart: always
    command: 'forever -w --minUptime 5000 --spinSleepTime 3000 --killSignal SIGTERM server.js'
```

```
# Dockerfile
FROM node:10.12.0

WORKDIR /usr/src/app

RUN npm install forever -g
```

```
// server.js
process.on('SIGTERM', function () { console.log('Received SIGTERM'); process.exit(0); });
setInterval(() => console.log('.'));
```

Start the above with `docker-compose up` everything is running fine.

Current behavior:

When `Ctrl-C` is pressed, Docker sends SIGTERM immediately and nothing happens. After 10s Docker sends SIGKILL and this is the moment when both forever and my app stop.

Expected behavior;

When `Ctrl-C` is pressed, Docker sends SIGTERM immediately and forever should forward SIGTERM to the node process immediately IMO.
